version: "3"
services:
  hub:
    image: selenium/hub:4.8.1
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.8.1
    shm_size: '3g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    volumes:
      - ./output:/usr/share/cucumber/test-output/